### ISSUE TITLE
Predicted boxes or scores contain Inf/NaN. Training has diverged.

### ISSUE THREAD

**Issue by Stlve** [XXX-YES/FSOD#1]
Hello! I am happy that you are able to open source the code for your paper, but I am having some problems, when I am running the DIOR dataset, when I run the piece that introduces self-distillation, it always explodes in gradient and I would like to ask why is this?

**Comment by woody-panda** [comment]
Hi, you can use the pretrained weight of ResNet-50. The results are similar. I have updated the relevant information.
