### ISSUE TITLE
There is no ChestX datasets in the uploaded preprocessed dataset zip files in the google drive

### ISSUE THREAD

**Issue by generalvisionyyt** [XXX-YES/FSOD#2]
Thanks for your meaningful and interesting works.
I find that there is no ChestX datasets in the uploaded preprocessed dataset zip files uploaded to the google drive([here](https://drive.google.com/file/d/1C-_V6wBO--m_Qy1ll2WXmWb0VaeWDVPU/view?usp=sharing)).
Could you update this file to fix this problem?

**Comment by woody-panda** [comment]
Hi, we do not plan to report performance on the ChestX dataset. See the new version of our paper https://arxiv.org/pdf/2210.05311v2.pdf.

**Comment by MrCrightH** [comment]
hello, i can't upload the dataset from the link because of the Permissions, how can you upload them.
