### ISSUE TITLE
datasets can't install

### ISSUE THREAD

**Issue by MrCrightH** [XXX-YES/FSOD#3]
hello !would you like to share the datasets in annother way. I can't install it because the jurisdiction. thank you

**Comment by woody-panda** [comment]
Have you solved the problem with the datasets download? I can upload the dataset to Baidu Cloud, but it is very slow

**Comment by lyxdlut** [comment]
can you upload the only dior dataset? thank you.

**Comment by lyxdlut** [comment]
Or can you upload the three datasets on baidu cloud seperately?

**Comment by wqian11** [comment]
> Have you solved the problem with the datasets download? I can upload the dataset to Baidu Cloud, but it is very slow

I can't use the cloud to download, can you use Baidu cloud to share, thank you

**Comment by woody-panda** [comment]
Hi, see the following link.

链接: https://pan.baidu.com/s/1Pi2no3cpx8P_y0zjGrNMrA 
提取码: uer8

**Comment by wqian11** [comment]
太感谢啦，谢谢你



---Original---
From: ***@***.***&gt;
Date: Tue, May 23, 2023 02:38 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [FSOD/CD-FSOD] datasets can't install (Issue #3)




 
Hi, see the following link.
 
链接: https://pan.baidu.com/s/1Pi2no3cpx8P_y0zjGrNMrA
 提取码: uer8
