### ISSUE TITLE
The number of training images UODD dataset.

### ISSUE THREAD

**Issue by lovelyqian** [XXX-YES/FSOD#4]
Hi, thanks for your work and codes. However, I have a question about the number of training images of the UODD dataset.  It is supposed to have 3194 training images (as indicated by this repo), however, I find there are only 2688 training images. (while the training doesn't cause the error of "missing image". Could you help check this issue? Does it mean that the number of images actually being used for training is indeed 2688? Thanks!

**Comment by woody-panda** [comment]
Hi,

The lack of images does not affect the training. Since it is few-shot learning, the data used for fine-tuning and fine-tuning are only a few specified images. Thanks for your attention, I will check this issue as soon as possible.
